services:
  db:
    image: postgres:15-alpine
    container_name: medtrack-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: medtrack-backend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db:5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./interface-react
    container_name: medtrack-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./interface-react:/app
      - /app/node_modules # Evita sobrescrever os pacotes instalados
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm start
    depends_on:
      - backend

volumes:
  postgres_data:
